---
- name: clone the {{ package_name }} aur repository
  git:
    repo: "https://aur.archlinux.org/{{ package_name }}.git"
    dest: "{{ ansible_facts.env.HOME }}/git/aur/{{ package_name }}"
  register: aur_repo

- name: install/update {{ package_name }}
  when: aur_repo.changed
  command: makepkg --syncdeps --install --noconfirm
  args:
    chdir: "{{ ansible_facts.env.HOME }}/git/aur/{{ package_name }}"
